alpha = _{ 'a'..'z' | 'A'..'Z' }
digit = _{ '0'..'9' }

ident = _{ (alpha | digit)+ }

html_words = _{ ident ~ ("-" ~ ident)* }
tag_name = { html_words }
attr_name = { html_words }

attr = { html_words ~ "=\"" ~ (ANY+) ~ "\"" }

closing_bracket = { ">" }
starting_tag = { "<" ~ tag_name ~ ">" }
closing_tag = { "</" ~ tag_name ~ ">" }

text = { (ident | WHITE_SPACE)+ }
text_node = { starting_tag ~ text? ~ closing_tag }

// ident_list = _{ !digit ~ ident ~ (" " ~ ident)+ }
