[package]
name = "fervid_lsp"
version = "0.1.0"
edition = "2024"

[dependencies]

dashmap = "6.1.0"
env_logger = "0.11.8"
fervid_core = { path="../fervid_core", version = "0.2" }
fervid_parser = { path="../fervid_parser", version = "0.2" }
fervid_transform = { path="../fervid_transform", version = "0.2" }
fxhash = { workspace = true }
log = "0.4.27"
ropey = "1.6.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
swc_core = { workspace = true, features = ["common", "ecma_ast"] }
swc_ecma_parser = { workspace = true }
tokio = { version = "1.47.1", features = ["full"] }
tower-lsp = { version = "0.20.0", features = ["proposed"] }
