name: Code Spell Check
on: [pull_request]

jobs:
  code-spell-check:
    name: Spell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 20

      - name: Run Spell Check
        shell: bash
        run: npx cspell "**" --gitignore
