name: Tests
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  cargo-check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Cache rust artifacts
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: cargo-check

      - name: Run cargo check
        run: cargo check --color always --all --all-targets

  cargo-test:
    name: Test - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          # Sync with rust-toolchain.toml
          toolchain: nightly-2025-04-16
      - name: Cache rust artifacts
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: cargo-test-${{ matrix.os }}

      - name: Run cargo test
        # Exclude NAPI crate due to build errors on macos and because it has separate test jobs
        run: cargo test --workspace --all-targets --exclude fervid_napi
